services:
  backend:
    build: ./backend
    container_name: expense-backend-container
    ports:
      - "5000:5000"
    env_file:
       - ./backend/.env
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: expense-frontend-container
    ports:
      - "80:80"
    restart: unless-stopped
  